version: 2.1
jobs:
  build:
    docker:
      - image: imrehg/archlinux-makepkg
    steps:
      - run:
          name: init pacman
          command: |
            sudo pacman -Syu --noconfirm
            sudo pacman -S git openssh
      - checkout
      - run: namcap PKGBUILD
      - run: makepkg -sci --noconfirm
      - persist_to_workspace:
          root: .
          paths:
            - "opencv-tesseract*"
  deploy:
    docker:
      - image: cimg/go:1.15
    steps:
      - attach_workspace:
          at: ./artifacts
      - run: ls -la
      - run: |
          go get github.com/tcnksm/ghr
          ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+/
