version: 2.1
jobs:
  build:
    docker:
      - image: imrehg/archlinux-makepkg
    steps:
      - run:
          name: init pacman
          command: |
            sudo pacman -Syu --noconfirm
            sudo pacman -S --noconfirm git openssh
      - checkout
      - run: namcap PKGBUILD
      - run: makepkg -sci --noconfirm
      - run: ./.circleci/collect_info.sh
      - persist_to_workspace:
          root: .
          paths:
            - "opencv-tesseract*"
            - "on_tag.txt"
            - "tag.txt"
  deploy:
    docker:
      - image: cimg/go:1.15
    steps:
      - attach_workspace:
          at: ./artifacts
      - run: ls -la artifacts
      - run:
          name: create github release when on tag
          command: |
            if [ $(cat ./artifacts/on_tag.txt) -eq "0" ]; then
              VERSION=$(cat ./artifacts/tag.txt)
              rm ./artifacts/*.txt
              go get github.com/tcnksm/ghr
              ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete "${VERSION}" ./artifacts/
            else
              echo "not executed"
            fi
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
